# Generated by Django 5.0.6 on 2024-10-10 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, max_length=50, null=True, verbose_name='Долгота')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Высота')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winter', models.CharField(choices=[('1A', '1A'), ('1B', '1Б'), ('1A', '2A'), ('2B', '2Б'), ('3A', '3A'), ('3B', '3Б')], max_length=2)),
                ('spring', models.CharField(choices=[('1A', '1A'), ('1B', '1Б'), ('1A', '2A'), ('2B', '2Б'), ('3A', '3A'), ('3B', '3Б')], max_length=2)),
                ('summer', models.CharField(choices=[('1A', '1A'), ('1B', '1Б'), ('1A', '2A'), ('2B', '2Б'), ('3A', '3A'), ('3B', '3Б')], max_length=2)),
                ('autumn', models.CharField(choices=[('1A', '1A'), ('1B', '1Б'), ('1A', '2A'), ('2B', '2Б'), ('3A', '3A'), ('3B', '3Б')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='PassUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=64, unique=True)),
                ('fam', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('otc', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Pereval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beauty_title', models.CharField(max_length=255, verbose_name='Название препятствия')),
                ('title', models.CharField(max_length=255, verbose_name='Название вершины')),
                ('other_titles', models.CharField(max_length=255, verbose_name='Другое название')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'новый'), ('pending', 'модератор взял в работу'), ('accepted', 'модерация прошла успешно'), ('rejected', 'модерация прошла, информация не принята')], default='new', max_length=10)),
                ('connect', models.TextField(blank=True, null=True)),
                ('coords', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pereval.coords')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pereval.level')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='pereval.passuser')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('pereval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pereval.pereval')),
            ],
        ),
    ]
